version: "3.3"

services:
  wedding:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules